# https://mlflow.org
# To run the server, run the following command from logs/mlflow directory:
#   mlflow server --host 127.0.0.1 --port 8585

mlflow:
  _target_: lightning.pytorch.loggers.mlflow.MLFlowLogger
  experiment_name: ${name}
  run_name: ""
  tracking_uri: ${paths.log_dir}/mlflow/mlruns # run `mlflow ui` command inside the `logs/mlflow/` dir to open the UI
  tags: null
  # save_dir: "./mlruns"
  prefix: ""
  artifact_location: null
#  run_id: ""
